### ISSUE TITLE
Recommended composer installations fails due to php-parallel-lint not existing

### ISSUE THREAD

**Issue by dylanh724** [s7eph4n/SimpleBatchUpload#10]
![image](https://user-images.githubusercontent.com/8840024/34638397-7212506c-f305-11e7-8721-7cdf7334aaed.png)

**Comment by s7eph4n** [comment]
Looks like you have permission issues on your filesystem. jakub-onderka/php-parallel-lint is a direct MW requirement. I do not think it has anything to do with SimpleBatchUpload.
