### ISSUE TITLE
Instructions are SUPER lacking and dated

### ISSUE THREAD

**Issue by dylanh724** [s7eph4n/SimpleBatchUpload#11]
https://www.mediawiki.org/wiki/Extension:SimpleBatchUpload

I'd update this if I knew how to even add this. Can't add via composer due to https://github.com/s7eph4n/SimpleBatchUpload/issues/10 and regular extension doesn't even work.

Why not just be simple and allow for a git clone like everyone else?
  
EDIT: I noticed your production files are actually in /src instead of /release ? This is very misleading

**Comment by s7eph4n** [comment]
Is this a bug report or a rant?

If you have issues with the documentation, please ask specific questions. "SUPER lacking and dated" is not particularly helpful.

> Why not just be simple and allow for a git clone like everyone else?
1. Dependency management.
2. Keeping extension up to date using Git is a major PITA.
3. I like Composer.

> EDIT: I noticed your production files are actually in /src instead of /release ? This is very misleading

Welcome to PHP.
