### ISSUE TITLE
Cannot install simple batch upload by the tar file

### ISSUE THREAD

**Issue by LesleyLai** [s7eph4n/SimpleBatchUpload#5]
I installed the extension by the "alternative" method, but it failed. Here is the error message in php.log:

> PHP Fatal error:  Uncaught exception 'Exception' with message '{{My Mediawiki Root Path}}/extensions/SimpleBatchUpload/extension.json is not a valid JSON file.' in {{My Mediawiki Root Path}}/includes/registration/ExtensionRegistry.php:176        
> Stack trace:
> #0 {{My Mediawiki Root Path}}/includes/registration/ExtensionRegistry.php(127): ExtensionRegistry->readFromQueue(Array)        
> #1 {{My Mediawiki Root Path}}/includes/Setup.php(39): ExtensionRegistry->loadFromQueue()        
> #2 {{My Mediawiki Root Path}}/includes/WebStart.php(137): require_once('/var/lib/opensh...')        
> #3 {{My Mediawiki Root Path}}/index.php(38): require('/var/lib/opensh...')        
> #4 {main}        
> thrown in {{My Mediawiki Root Path}}/includes/registration/ExtensionRegistry.php on line 176

I omitted my mediawiki root path. It is weird since "SimpleBatchUpload/extension.json" is a valid JSON.

**Comment by s7eph4n** [comment]
Could you post your `extension.json`?

Also which exact version of SimpleBatchUpload and MediaWiki are you using?

**Comment by LesleyLai** [comment]
The `extension.json` is below, I have not modified it.

```json
{
	"name": "SimpleBatchUpload",
	"version": "1.1.0",
	"author": [
		"[http://www.mediawiki.org/wiki/User:F.trott Stephan Gambke]"
	],
	"url": "https://www.mediawiki.org/wiki/Extension:SimpleBatchUpload",
	"descriptionmsg": "simplebatchupload-desc",
	"license-name": "GPL-2.0+",
	"type": "specialpage",
	"requires": {
		"MediaWiki": "~1.26"
	},
	"MessagesDirs": {
		"SimpleBatchUpload": [
			"i18n"
		]
	},
	"callback": "SimpleBatchUpload\\SimpleBatchUpload::initCallback",
	"manifest_version": 1,
	"load_composer_autoloader" : true
}
```

My Mediawiki version is `1.26.2`. And I am using SimpleBatchUpload Release 1.1.0, the actually file is "SimpleBatchUpload.1.1.0.with.dependencies.tar.gz".

**Comment by s7eph4n** [comment]
Just tried it and it works for me. Could this be a rights problem?

**Comment by s7eph4n** [comment]
Turns out that the tar ball was borked. Autoloading of classes did not work.
Could you try https://github.com/s7eph4n/SimpleBatchUpload/releases/tag/1.2.0-RC1 and see if it works for you?

**Comment by LesleyLai** [comment]
It worked. Thank you.
